### ISSUE TITLE
Source Code available?

### ISSUE THREAD

**Issue by jubudu** [HomeKidd/ESP8266-HomeKit-Air-Quality-Sensor-Elgato-Eve-Room#1]
Hello, 
first of all thank you for this interesting IOT-sensor design!

I would like, to use another, cheaper sensor like the MQ135.
Is it possible, that you upload the sources in order to code for my purposes?

**Comment by HomeKidd** [comment]
Currently I’m not planning to add support for the MQ135 because these sensors are not as accurate as my sensors (MQ135 is a simple resistance based analog sensor)😁

But some else has [source code](https://github.com/maccoylton/esp-homekit-air-quality-sensor) for that sensor👌

**Comment by HomeKidd** [comment]
Also I’ve forget to mention that i’m planning to add support for other, cheaper sensors (CCS811 and maybe BME680)✌️🤓
