### ISSUE TITLE
Sensor range: differences between Data Sheet and Wiki

### ISSUE THREAD

**Issue by jonalbr** [HomeKidd/ESP8266-HomeKit-Air-Quality-Sensor-Elgato-Eve-Room#10]
Hi,
according to the Data Sheet the range of the AMS IAQ-Core Sensor is as followed:
```
Sensing range:
450 – 2000 ppm CO2 equivalents
125 – 600 ppb TVOC equivalents
```
Your project uses higher CO2 equivalents (2100 ppm for 'Poor'). How is this supported?
[https://www.mouser.de/datasheet/2/1081/iaQ_Core_Datasheet-1890457.pdf](url)

Best Regards, Jonas

**Comment by HomeKidd** [comment]
Hi!
Theres nothing special about the sensing range, take a look at the datasheet again:

![119DFD60-81F1-4A61-9DBA-97C6FF2A38BF](https://user-images.githubusercontent.com/53994826/108180769-71082100-7107-11eb-9aad-1cda0e315dd4.jpeg)

Values over 2000 ppm also provided, also the ranges for the Air Quality is provided by Eve, i’ve used the same thresholds that Elgato used _(and also the IAQ sensor is the same one what Eve used in the 1st gen Eve Room)_
