### ISSUE TITLE
Can you post some pictures of the PCB after you put all the pieces on the board?

### ISSUE THREAD

**Issue by jonalbr** [HomeKidd/ESP8266-HomeKit-Air-Quality-Sensor-Elgato-Eve-Room#11]
Hi, thanks for your recent help. 
This is the first projekt of this kind for me. Could you please post some pictures of the stocked PCB? I'm not sure if I understand everything right and would like to check. I'm trying to replicate the version including the OLED display.

Further, why did you change the DHT22 sensor to the SHT31 sensor? Is the quality better?

Thank you so much in advance
Jonas

**Comment by HomeKidd** [comment]
Hi!

I have pictures on my [Instagram profile](https://www.instagram.com/p/B7tUfcwH35s/?utm_source=ig_web_copy_link)! 🤓

SHT3x is a digital, i2c bus device with much more accuracy than the the DHT22. The DHT22 is a low cost device and the quality varies over the sensors, not so accurate. The SHT30 is also a low cost device with lower accuracy, the  SHT31 is the perfect one with the best price/value ratio (has higher accuracy with not much more cost than the SHT30) and the SHT35 is the highest accuracy sensor but with higher price
