### ISSUE TITLE
Serial | USB TTL adapter

### ISSUE THREAD

**Issue by jonalbr** [HomeKidd/ESP8266-HomeKit-Air-Quality-Sensor-Elgato-Eve-Room#12]
Hi,
how did you connect your USB TTL adapter to the serial of the 2.x.x PCB as there are only 4 out of 8 pins? I guessed you used jumper cables, however what ports should I connect to each other?
Best regards Jonas

**Comment by HomeKidd** [comment]
Hi!

You only need 3.3V, GND, RX and TX from the serial adapter and put the ESP in [bootloder mode](https://github.com/HomeKidd/ESP8266-HomeKit-Air-Quality-Sensor-Elgato-Eve-Room/wiki/Build-Instructions#putting-device-into-flash-mode) by pushing and holding the button before plugging the USB adapter into you computer.

![5E91F94F-296B-4256-AACF-A5DDF4B431BA](https://user-images.githubusercontent.com/53994826/108688601-65966a80-74f8-11eb-8572-25ae127a52ff.jpeg)

**Comment by jonalbr** [comment]
The button on the PCB or should there be a button on the adapter?

**Comment by HomeKidd** [comment]
The button on the PCB ✌️

**Comment by jonalbr** [comment]
Pushing the button; powering; releasing the button; connecting to USB port? 
Is that correct? 
Thanks for your help!✌️
