### ISSUE TITLE
IR Remote V1.3.1

### ISSUE THREAD

**Issue by zsoltturcsan** [HomeKidd/ESP8266-HomeKit-Air-Quality-Sensor-Elgato-Eve-Room#24]
SZia,
Sajnos a IR Remote V1.3.1 vezérlőhöz nem találok beültetési rajzot, vásároltam pár darabot a pcbway-ről.
Segítenél?
Előre is köszönöm!

**Comment by HomeKidd** [comment]
Üdv! 
Itt a teljes BOM fájl!
[BOM_ESP8266-HomeKit-IR-Remote_2024-04-09.csv](https://github.com/HomeKidd/ESP8266-HomeKit-Air-Quality-Sensor-Elgato-Eve-Room/files/14919385/BOM_ESP8266-HomeKit-IR-Remote_2024-04-09.csv)

**Comment by zsoltturcsan** [comment]
Szia, 

Köszönöm! 
Hibakereséshez és programozáshoz szeretnék még kapcsolási rajzot is kérni. 

Üdvözlettel: 

Turcsán Zsolt

**Comment by HomeKidd** [comment]
[Schematic_ESP8266-HomeKit-IR-Remote_2024-04-11.pdf](https://github.com/HomeKidd/ESP8266-HomeKit-Air-Quality-Sensor-Elgato-Eve-Room/files/14944458/Schematic_ESP8266-HomeKit-IR-Remote_2024-04-11.pdf)
