### ISSUE TITLE
Firmware Version 

### ISSUE THREAD

**Issue by duxhomines** [HomeKidd/ESP8266-HomeKit-Air-Quality-Sensor-Elgato-Eve-Room#5]
I am having a bit of trouble connecting the display to the sensor. After closer inspection, Homekit reports that the firmware version is 1.0.3. Are the links to the bin files the latest version? Is there also a way to access older bin files (can't seem to find them in the compressed folders)? Thanks!

**Comment by HomeKidd** [comment]
Latest main.bin file can be downloaded from the [Releases tab](https://github.com/HomeKidd/ESP8266-HomeKit-Air-Quality-Sensor-Elgato-Eve-Room/releases) and also marked in the [readme]( https://github.com/HomeKidd/ESP8266-HomeKit-Air-Quality-Sensor-Elgato-Eve-Room/blob/master/README.md) too🙌
